# Preparation of bacterial culture and formalin-killed vaccines {#cross}

<style>
body {
text-align: justify}
</style>

## Recovery of the two strains S.agalactiae and A.veronii using TSA/TSB for 24h

The two bacterial isolates used in this research are from Thailand. They were previously isolated from a diseased Nile tilapia.

The two isolates are conserved in frozen glycerol and therefore must be recovered on a rich medium such as tryptic soy agar (TSA) or tryptic
soy broth (TSB) for 24 h at 30 ???C

## Bacterial culture

For the formulation of the inactivated bacterial vaccines, the bacteria will be put in culture in a volume of around 300mL of tryptic soy broth (TSB) for at least a day 24 h at 30???C
under agitation et oxygenation.

### Growth-curves
### Count viable and dead cells
### Estimate biomass with spectrophotometer for ??=600 nm

Once the growth is achieved, the bacterial cells of S.agalactiae and A.veronii will be inactivated by adding formalin to a final concentration of 3%(v/v) and incubated overnight at 4 ???C (the longer the better).

## Production of inactivated vaccines

### Production of vaccine Sa 

### Production of vaccine Av  

### Production of vaccine Sa + Av 

### Production of vaccine Control 
